export const slots=['До завтрака','После завтрака','До обеда','После обеда','До ужина','После ужина','Другое'];
export type Entry={id:string;date:string;time:string;slot:number;value:number;food:string;carbs:string;mood:number;note:string;photo:string;after:number};
export type Day={mood:number;note:string;sleep:string;activity:string;stress:string;extra:string};
export type Settings={name:string;unit:'mmol'|'mg';dark:boolean;before:[string,string];after:[string,string];plan:string;reminders:{on:boolean;time:string}[];notify:boolean};
export type Data={entries:Entry[];days:Record<string,Day>;settings:Settings};
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const initial:Data={entries:[],days:{},settings:{name:'',unit:'mmol',dark:false,before:['',''],after:['',''],plan:'',notify:false,reminders:['07:00','09:00','12:00','14:00','18:00','20:00'].map(time=>({on:false,time}))}};
export const emptyDay:Day={mood:1,note:'',sleep:'',activity:'',stress:'',extra:''};
export function readDB():Promise<Data>{return new Promise((resolve,reject)=>{const req=indexedDB.open('sugar-bloom',1);req.onupgradeneeded=()=>req.result.createObjectStore('diary');req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result;const r=db.transaction('diary').objectStore('diary').get('data');r.onsuccess=()=>{resolve(r.result??structuredClone(initial));db.close()};r.onerror=()=>reject(r.error)}})}
export function writeDB(data:Data):Promise<void>{return new Promise((resolve,reject)=>{const req=indexedDB.open('sugar-bloom',1);req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result;const t=db.transaction('diary','readwrite');t.objectStore('diary').put(data,'data');t.oncomplete=()=>{db.close();resolve()};t.onerror=()=>reject(t.error)}})}
export function status(e:Entry,s:Settings){const range=e.slot%2===1&&e.slot<6?s.after:s.before;if(!range[0]||!range[1]||!Number.isFinite(+range[0])||!Number.isFinite(+range[1])||+range[0]>=+range[1]||e.slot===6)return 'unset';return e.value<+range[0]?'low':e.value>+range[1]?'high':'in'}
export function demoData():Data{const d=structuredClone(initial);d.settings.name='Анна';d.settings.before=['4','6'];d.settings.after=['4','8'];for(let i=13;i>=0;i--){const date=new Date();date.setDate(date.getDate()-i);const key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;for(let j=0;j<(i===0?4:6);j++)d.entries.push({id:`demo-${i}-${j}`,date:key,time:['07:05','08:42','12:15','13:48','18:10','20:05'][j],slot:j,value:+([4.8,5.1,4.9,6.2,4.7,5.9][j]+Math.sin(i+j)*.5).toFixed(1),food:j===1?'Овсянка с ягодами, кофе':j===3?'Паста с курицей':'',carbs:j===1?'35':'',mood:1,note:'',photo:'',after:2});d.days[key]={...emptyDay,note:'Сегодня нашла время для прогулки и отдыха 💙',sleep:'7 ч 30 мин',activity:'Прогулка 40 мин',stress:'Умеренный'}}return d}
export function validateData(x:unknown):x is Data{if(!x||typeof x!=='object')return false;const d=x as Data;const text=(v:unknown)=>typeof v==='string';const range=(v:unknown)=>Array.isArray(v)&&v.length===2&&v.every(text);return Array.isArray(d.entries)&&d.entries.length<=100000&&d.entries.every(e=>e&&text(e.id)&&/^\d{4}-\d{2}-\d{2}$/.test(e.date)&&/^\d{2}:\d{2}$/.test(e.time)&&Number.isFinite(e.value)&&e.value>0&&e.value<=60&&Number.isInteger(e.slot)&&e.slot>=0&&e.slot<=6&&[e.food,e.carbs,e.note,e.photo].every(text)&&Number.isInteger(e.mood)&&e.mood>=0&&e.mood<=4)&&!!d.days&&typeof d.days==='object'&&!Array.isArray(d.days)&&Object.values(d.days).every(day=>day&&[day.note,day.sleep,day.activity,day.stress,day.extra].every(text)&&Number.isInteger(day.mood)&&day.mood>=0&&day.mood<=4)&&!!d.settings&&text(d.settings.name)&&['mmol','mg'].includes(d.settings.unit)&&typeof d.settings.dark==='boolean'&&typeof d.settings.notify==='boolean'&&text(d.settings.plan)&&range(d.settings.before)&&range(d.settings.after)&&Array.isArray(d.settings.reminders)&&d.settings.reminders.length===6&&d.settings.reminders.every(r=>r&&typeof r.on==='boolean'&&/^\d{2}:\d{2}$/.test(r.time))}
